version: '3'
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - app-network
  client:
    build: ./client
    ports:
      - "4200:80"
    depends_on:
      - server
    networks:
      - app-network
networks:
  app-network:
    driver: bridge